# Generated by Django 6.0.1 on 2026-01-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_author_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
