# Generated by Django 6.0.1 on 2026-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_taskcontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontrol",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
