# Generated by Django 6.0.1 on 2026-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0008_author_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="url",
            field=models.URLField(max_length=400),
        ),
    ]
