# Generated by Django 6.0.1 on 2026-03-31 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0009_alter_review_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="content",
        ),
    ]
