# Generated by Django 6.0.1 on 2026-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0010_remove_review_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
