# Generated by Django 6.0.1 on 2026-04-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0011_parsercontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterboxdUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LetterboxdEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("date", models.DateTimeField()),
                (
                    "letterboxd_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="reviews.letterboxduser",
                    ),
                ),
            ],
            options={
                "unique_together": {("letterboxd_user", "title", "date")},
            },
        ),
    ]
