# Generated by Django 6.0.1 on 2026-04-14 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0012_letterboxduser_letterboxdentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="letterboxdentry",
            options={"ordering": ("-date",)},
        ),
    ]
