# Generated by Django 6.0.1 on 2026-02-17 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_date_joined_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
