# Generated by Django 6.0.1 on 2026-04-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_email_notifications"),
        ("reviews", "0012_letterboxduser_letterboxdentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="letterboxd_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="reviews.letterboxduser",
            ),
        ),
    ]
