# Generated by Django 6.0.1 on 2026-04-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_letterboxd_user"),
        ("reviews", "0013_alter_letterboxdentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="letterboxd_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="reviews.letterboxduser",
            ),
        ),
    ]
